### ISSUE TITLE
Error building the application with AIR 3.3

### ISSUE THREAD

**Issue by tangentlin** [jlopez/ane-testflight#3]
When I built the app with AIR 3.3, I got the following error:

ld: library not found for -lNativeLibrary
Compilation failed while executing : ld64

**Comment by bolom** [comment]
You should do that:

When building an .ipa, you must:

Extract the libNativeLibrary.a found inside the .ane at /META-INF/ANE/iPhone-ARM-lib.
Move this library into the Flex SDK at lib/aot/lib
Otherwise, linker errors will ensue. Alternatively, you can build your .ipa using the air-mk makefiles which will do this automatically.
